### ISSUE TITLE
crashes entire stack if given hypercore key

### ISSUE THREAD

**Issue by karissa** [datproject/datfolder#372]
Navigate to 

`dat.land/view/503cf9e12d8ae49a07568d90f04bbdbfa3f1998ab97ed2b5143c1f3f69ec052f`

the entire stack crashes and then you see:
```
Error: Unknown message type: unknown
    at getEncoding (/Users/karissa/node_modules/dat.land/node_modules/hyperdrive-encoding/index.js:24:19)
    at Object.decode (/Users/karissa/node_modules/dat.land/node_modules/hyperdrive-encoding/index.js:32:13)
    at /Users/karissa/node_modules/dat.land/node_modules/hyperdrive/archive.js:524:30
    at done (/Users/karissa/node_modules/dat.land/node_modules/hypercore/lib/feed.js:190:5)
    at /Users/karissa/node_modules/dat.land/node_modules/levelup/lib/levelup.js:230:7
    at Immediate.callNext (/Users/karissa/node_modules/dat.land/node_modules/memdown/memdown.js:173:5)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by karissa** [comment]
related to https://github.com/karissa/hyperhealth/issues/2

**Comment by karissa** [comment]
fixed by https://github.com/datproject/datfolder/commit/654bf989a151217f2f47a11d1df53bc976bf8850, but opening an issue that will give a better error message for hypercores (TBD)
